-- Gestões do Portal do Colaborador
-- Gerado de "Empregados.xlsx" (abas Empregados e PJ), somente colaboradores ATIVOS.
-- 135 colaboradores · 30 com segundo gestor.
--
-- Pré-requisitos: migrations 20260903120100 (manager_id) e 20260903121100
-- (co_manager_id) aplicadas, e IGOR ASTORI já cadastrado como colaborador.
--
-- Rode na ordem. O BLOCO 1 só confere e não altera nada.

-- Normalização das comparações: minúsculo, sem acento, espaços comprimidos.
-- Vale só para esta sessão.
CREATE OR REPLACE FUNCTION pg_temp.wg_norm(t text) RETURNS text
LANGUAGE sql IMMUTABLE AS $fn$
  SELECT btrim(regexp_replace(
    lower(translate(t, 'ÁÀÂÃÄáàâãäÉÈÊËéèêëÍÌÎÏíìîïÓÒÔÕÖóòôõöÚÙÛÜúùûüÇçÑñ', 'AAAAAaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUUuuuuCcNn')),
    '\s+', ' ', 'g'))
$fn$;

DROP TABLE IF EXISTS wg_gestoes;
CREATE TEMP TABLE wg_gestoes (colaborador text, gestor text, cogestor text);
INSERT INTO wg_gestoes (colaborador, gestor, cogestor) VALUES
  ('ELISANGELA DA SILVA PALAGI', 'PAULO HENRIQUE DOS SANTOS', NULL),
  ('HENRIQUE ARAÚJO', 'PAULO HENRIQUE DOS SANTOS', NULL),
  ('FERNANDO NATA MORAES LIMA', 'ELDERI VASCO FELIX', NULL),
  ('GUILHERME BRILHANTE FELIZATE', 'ELDERI VASCO FELIX', NULL),
  ('MARCELO COUTINHO MUNIZ', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('MICHAEL LUCIANO MONTREZOL DE SOUZA', 'ELDERI VASCO FELIX', NULL),
  ('EDUARDO CALOI ACORSI', 'KLEBER TERNEL DE SOUZA', NULL),
  ('KARINA ADRIAN DA SILVA', 'KATIANE ANDREATA', NULL),
  ('VICTOR RIBEIRO MENDES PALHANO', 'KLEBER TERNEL DE SOUZA', NULL),
  ('WINICIUS NAFTALI DE OLIVEIRA', 'ELDERI VASCO FELIX', NULL),
  ('ELDERI VASCO FELIX', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('MARCOS ANTÔNIO DE ALMEIDA', 'ELDERI VASCO FELIX', NULL),
  ('THIAGO GABRIEL MONTREZOL BOHRER', 'ELDERI VASCO FELIX', NULL),
  ('ADRIANO DOS REIS RODRIGUES MIRANDA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('FERNANDO DE ALBUQUERQUE FERREIRA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('GABRIEL DE CERQUEIRA ROCHA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('JOSE ANDERSON GRACILIANO TENORIO', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('ROBSON LEMES DE SA', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('RODRIGO DE LIMA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('SEBASTIÃO CARLOS GRILLO DA SILVA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('VITOR DA SILVA SOARES', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('WAGNER APARECIDA GOMES', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('YURI LISBOA DOS SANTOS', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('ADRIANO FERREIRA SILVA', 'IGOR ASTORI', NULL),
  ('ALESSANDRA MAXIMO DE OLIVEIRA MACHADO', 'SIMONE PAULINO DE SOUZA GARCIA', NULL),
  ('ATILA SOARES LIMA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('BEATRIZ DOS SANTOS ROSA', 'SIMONE PAULINO DE SOUZA GARCIA', NULL),
  ('EDNEI SANTOS DA SILVA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('ISRAEL BASTOS DA SILVA', 'IGOR ASTORI', NULL),
  ('JULIO CESAR GOMES TEIXEIRA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('JULIO CEZAR ALEXANDRE ADÃO RODRIGUES DA SILVA COSTA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('LUAN HENRIQUE NASCIMENTO DE ASSIS', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('MARCIO OLIVEIRA DOS SANTOS', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('ROBERTO CARLOS ANDRE', 'IGOR ASTORI', NULL),
  ('RUI DA SILVA SANT ANA', 'IGOR ASTORI', NULL),
  ('SIMONE PAULINO DE SOUZA GARCIA', 'KATIANE ANDREATA', NULL),
  ('TIAGO ANTONIO DA ROCHA', 'IGOR ASTORI', NULL),
  ('WEVERTON NINA MACIEIRA', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('RONALD DOS SANTOS', 'JOSE ANDERSON GRACILIANO TENORIO', 'ROBSON LEMES DE SA'),
  ('DERLANIO SANTOS SILVA', 'PAULO HENRIQUE DOS SANTOS', NULL),
  ('LEANDRO MIRIANI', 'PAULO HENRIQUE DOS SANTOS', NULL),
  ('ANDRE LOURENCO', 'GUSTAVO SEBASTIAO FERREIRA', NULL),
  ('DIEGO GOUVEIA DOS SANTOS', 'GUSTAVO SEBASTIAO FERREIRA', NULL),
  ('FERNANDO FERREIRA NOVAES', 'GUSTAVO SEBASTIAO FERREIRA', NULL),
  ('ALISSON DE BARROS NARLOCH', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('AMANDA VITORIA DA SILVA ROSA', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('GUSTAVO SEBASTIAO FERREIRA', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('ANDRE LUIS MATUCHESKI TOZO', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('ANDREIA BATISTA CAJU STRAMBECK', 'DANIEL MARCHIOTI DA SILVA', NULL),
  ('ARMANDO DE ANDRADE DE RIBEIRO', 'IGOR ASTORI', NULL),
  ('BIANKA BANQUES RODRIGUES SILVA', 'MARIA EDUARDA FERREIRA', NULL),
  ('CELIO DE BRITTO', 'ARMANDO DE ANDRADE DE RIBEIRO', NULL),
  ('DANIELLA MIRAVALHES FERNANDES', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('DARLENE DA SILVA ANDRADE', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('RAFAEL FONTES CORREIA', 'GUSTAVO SEBASTIAO FERREIRA', NULL),
  ('EDUARDA CAROLINE SCHMIDT', 'GISELE GARCIA RIBEIRO', NULL),
  ('FELIPE SANTOS DE CRISTO', 'GUSTAVO SEBASTIAO FERREIRA', NULL),
  ('TIAGO DOS SANTOS PEREIRA', 'GUSTAVO SEBASTIAO FERREIRA', NULL),
  ('GABRIEL HENRIQUE DE ANDRADE', 'ARMANDO DE ANDRADE DE RIBEIRO', NULL),
  ('GUILHERME LAWIN INGLES', 'ARMANDO DE ANDRADE DE RIBEIRO', NULL),
  ('ISABELLY PRADO DOS SANTOS', 'MARIA EDUARDA FERREIRA', NULL),
  ('JENIFER DE OLIVEIRA', 'MARIA EDUARDA FERREIRA', NULL),
  ('JESSIANE LARA ALVES', 'DANIEL MARCHIOTI DA SILVA', NULL),
  ('JESSICA MEDEIROS DA SILVA', 'GISELE GARCIA RIBEIRO', NULL),
  ('JOSE WILLIAN BENVINDO DA SILVA', 'DANIEL MARCHIOTI DA SILVA', NULL),
  ('JULIANA OLENICK DE SOUZA TEIXEIRA', 'MARIA EDUARDA FERREIRA', NULL),
  ('JULLIANA PACHECO DA ROCHA', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('JULYENY VICTÓRIA MOURA CARVALHO', 'DANIEL MARCHIOTI DA SILVA', NULL),
  ('KADYJA GEOVANA SILVA SANTOS', 'MARIA EDUARDA FERREIRA', NULL),
  ('KAMILA RODRIGUES DA SILVA', 'DANIEL MARCHIOTI DA SILVA', NULL),
  ('KEITY MAHARA OLIVEIRA DE GODOY DA COSTA', 'KATIANE ANDREATA', NULL),
  ('LARA DOMINGUES SILVA', 'MARIA EDUARDA FERREIRA', NULL),
  ('LEONARDO SETIM CORDEIRO DA CRUZ', 'GUSTAVO SEBASTIAO FERREIRA', NULL),
  ('MARIA EDUARDA DA SILVA SANTOS', 'GISELE GARCIA RIBEIRO', NULL),
  ('MARIA EDUARDA FERREIRA', 'KATIANE ANDREATA', NULL),
  ('MURILO BREMER TIERA', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('NICOLAS NICOLIO CAMARA', 'GISELE GARCIA RIBEIRO', NULL),
  ('PAULO ROBERTO BELARMINO SCACHETTI', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('RHADASSA SOUZA DA SILVEIRA', 'GISELE GARCIA RIBEIRO', NULL),
  ('ROBERT DA SILVA ROSA', 'PAULO HENRIQUE DOS SANTOS', NULL),
  ('SARA PEREIRA ROCHA', 'KATIANE ANDREATA', NULL),
  ('STHEFANY OLIVEIRA DA ROCHA CORREIA', 'DANIEL MARCHIOTI DA SILVA', NULL),
  ('THALIA HALINE DE LIMA', 'DANIEL MARCHIOTI DA SILVA', NULL),
  ('THIAGO DIAS EVANGELISTA', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('WELLINGTON SANTANA DE MIRANDA', 'GISELE GARCIA RIBEIRO', NULL),
  ('YASMIN KAEHLER', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('CAROLINE ALVES DA SILVA', 'MARIA EDUARDA FERREIRA', NULL),
  ('MAIARA APARECIDA CANDIDO', 'MARIA EDUARDA FERREIRA', NULL),
  ('NICOLE SCHMIDT DE MORAIS', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('ALESSANDRA ESCUDERO AVILA PERES', 'KATIANE ANDREATA', NULL),
  ('CLAUDIO RENE FERREIRA DOS SANTOS', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('EDUARDO DA COSTA', 'IGOR ASTORI', NULL),
  ('EDUARDO SQUETINI DE CAMPOS', 'IGOR ASTORI', NULL),
  ('FERNANDO ZAMPERLIN DA COSTA', 'IGOR ASTORI', NULL),
  ('GABRIEL HENRIQUE DE ANGELIS ARCARI', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('LUIZ FELIPE CARDOSO PEREIRA', 'IGOR ASTORI', NULL),
  ('MARCOS BARBOSA DA SILVA', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('PAULO HENRIQUE DOS SANTOS', 'ALINE ANDRESSA DA MOTA POPENDA', NULL),
  ('RAFAELA BARBOSA DE LIMA', 'ALESSANDRA ESCUDERO AVILA PERES', NULL),
  ('RIQUELME LOPES DOS SANTOS', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('RODOLFO DA SILVA NAUMANN', 'IGOR ASTORI', NULL),
  ('RODRIGO SOARES DE OLIVEIRA', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('SONIA MARIA SILVA PEREIRA', 'ALESSANDRA ESCUDERO AVILA PERES', NULL),
  ('VICTOR GRIENO NUNES DE LIMA', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('ANTONIO CARLOS SANTOS MARQUES', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('EDILSON ALEIXO DE OLIVEIRA', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('ELIVELTON SANTANA SANTOS', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('GABRIEL FERREIRA DOS SANTOS', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('GERSON CORREIA NUNES DA SILVA', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('GLEISON MARTINS DOS SANTOS', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('JONATAS DOS SANTOS SILVA', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('JOSE NILSON HONORATO DIAS', 'LERCIO DEYVID DA SILVA BARBOSA', 'MARITON JOSÉ DA SILVA SANTOS JUNIOR'),
  ('LERCIO DEYVID DA SILVA BARBOSA', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('MARITON JOSÉ DA SILVA SANTOS JUNIOR', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('JULIANA CRISTINE BRANDÃO DA SILVA', 'ALESSANDRA ESCUDERO AVILA PERES', NULL),
  ('DAYANE IVANOVSKI BUENO', 'KATIANE ANDREATA', NULL),
  ('JESSICA GLAUCIA BASTOS', 'IGOR ASTORI', NULL),
  ('JOSE EDUARDO VELOSO', 'CARLOS HENRIQUE GONCALVES', NULL),
  ('PABLO LOPES BRIAMONTE', 'IGOR ASTORI', NULL),
  ('ROSANA VICENTIN DE OLIVEIRA', 'IGOR ASTORI', NULL),
  ('VINICIUS MATHEUS DA COSTA AMADO', 'CARLOS HENRIQUE GONCALVES', NULL),
  ('CARLOS HENRIQUE GONCALVES', 'PAULO ROBERTO BELARMINO SCACHETTI', NULL),
  ('NELSON DOS SANTOS ALVES', 'CARLOS HENRIQUE GONCALVES', NULL),
  ('WEDERSON NUNES DA ROCHA', 'CARLOS HENRIQUE GONCALVES', NULL),
  ('GABRIEL FELICIANO', 'CARLOS HENRIQUE GONCALVES', NULL),
  ('RODRIGO FONSECA DOS SANTOS', 'CARLOS HENRIQUE GONCALVES', NULL),
  ('ALINE ANDRESSA DA MOTA POPENDA', 'IGOR ASTORI', NULL),
  ('CARLOS SQUETINI', 'IGOR ASTORI', NULL),
  ('DANIEL MARCHIOTI DA SILVA', 'IGOR ASTORI', NULL),
  ('GISELE GARCIA RIBEIRO', 'IGOR ASTORI', NULL),
  ('JOSÉ LUIZ MENDES', 'IGOR ASTORI', NULL),
  ('KATIANE ANDREATA', 'IGOR ASTORI', NULL),
  ('KLEBER TERNEL DE SOUZA', 'IGOR ASTORI', NULL),
  ('LUIZ CHICHINELLI', 'IGOR ASTORI', NULL),
  ('PRISCILA AMORIM DUTRA', 'IGOR ASTORI', NULL);

-- ─────────────────────────────────────────────────────────────────────
-- BLOCO 1 — conferência. Não altera nada.
-- Qualquer linha que aparecer aqui precisa ser resolvida antes do BLOCO 2.
-- ─────────────────────────────────────────────────────────────────────
SELECT 'colaborador não encontrado no portal' AS problema, g.colaborador AS nome
  FROM wg_gestoes g
 WHERE NOT EXISTS (SELECT 1 FROM public.employees e
                    WHERE pg_temp.wg_norm(e.name) = pg_temp.wg_norm(g.colaborador))
UNION ALL
SELECT DISTINCT 'gestor não encontrado no portal', g.gestor
  FROM wg_gestoes g
 WHERE NOT EXISTS (SELECT 1 FROM public.employees e
                    WHERE pg_temp.wg_norm(e.name) = pg_temp.wg_norm(g.gestor))
UNION ALL
SELECT DISTINCT 'segundo gestor não encontrado no portal', g.cogestor
  FROM wg_gestoes g
 WHERE g.cogestor IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM public.employees e
                    WHERE pg_temp.wg_norm(e.name) = pg_temp.wg_norm(g.cogestor))
UNION ALL
SELECT 'nome ambíguo no portal (mais de um registro)', g.colaborador
  FROM wg_gestoes g
 WHERE (SELECT count(*) FROM public.employees e
         WHERE pg_temp.wg_norm(e.name) = pg_temp.wg_norm(g.colaborador)) > 1
 ORDER BY 1, 2;

-- ─────────────────────────────────────────────────────────────────────
-- BLOCO 2 — grava. Só atualiza quem casou dos dois lados.
-- ─────────────────────────────────────────────────────────────────────
UPDATE public.employees AS e
   SET manager_id    = mg.id,
       co_manager_id = cg.id,
       updated_at    = now()
  FROM wg_gestoes g
  JOIN public.employees mg
    ON pg_temp.wg_norm(mg.name) = pg_temp.wg_norm(g.gestor)
  LEFT JOIN public.employees cg
    ON g.cogestor IS NOT NULL
   AND pg_temp.wg_norm(cg.name) = pg_temp.wg_norm(g.cogestor)
 WHERE pg_temp.wg_norm(e.name) = pg_temp.wg_norm(g.colaborador)
   AND e.id <> mg.id;

-- ─────────────────────────────────────────────────────────────────────
-- BLOCO 3 — resultado.
-- ─────────────────────────────────────────────────────────────────────
SELECT count(*) FILTER (WHERE manager_id IS NOT NULL)    AS com_gestor,
       count(*) FILTER (WHERE co_manager_id IS NOT NULL) AS com_segundo_gestor,
       count(*) FILTER (WHERE manager_id IS NULL)        AS sem_gestor
  FROM public.employees WHERE active;

SELECT e.name AS colaborador, m.name AS gestor, c.name AS segundo_gestor
  FROM public.employees e
  LEFT JOIN public.employees m ON m.id = e.manager_id
  LEFT JOIN public.employees c ON c.id = e.co_manager_id
 WHERE e.active
 ORDER BY m.name NULLS FIRST, e.name;
