/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as IntegracaoRouteImport } from './routes/integracao'
import { Route as GenteGestaoRouteImport } from './routes/gente-gestao'
import { Route as GateRouteImport } from './routes/gate'
import { Route as FormulariosRouteImport } from './routes/formularios'
import { Route as CulturaRouteImport } from './routes/cultura'
import { Route as ComunicadosRouteImport } from './routes/comunicados'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenteGestaoIndexRouteImport } from './routes/gente-gestao.index'
import { Route as ComunicadosIndexRouteImport } from './routes/comunicados.index'
import { Route as GenteGestaoPoliticasRouteImport } from './routes/gente-gestao.politicas'
import { Route as GenteGestaoHoleriteRouteImport } from './routes/gente-gestao.holerite'
import { Route as GenteGestaoFeriasRouteImport } from './routes/gente-gestao.ferias'
import { Route as GenteGestaoFaqRouteImport } from './routes/gente-gestao.faq'
import { Route as GenteGestaoDocumentosRouteImport } from './routes/gente-gestao.documentos'
import { Route as GenteGestaoContatosRouteImport } from './routes/gente-gestao.contatos'
import { Route as GenteGestaoCadastroRouteImport } from './routes/gente-gestao.cadastro'
import { Route as GenteGestaoBeneficiosRouteImport } from './routes/gente-gestao.beneficios'
import { Route as GenteGestaoAtestadosRouteImport } from './routes/gente-gestao.atestados'
import { Route as ComunicadosArquivoRouteImport } from './routes/comunicados.arquivo'
import { Route as ComunicadosIdRouteImport } from './routes/comunicados.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as ApiPublicFilesSplatRouteImport } from './routes/api/public/files/$'
import { Route as AuthenticatedAdminRecursoKeyRouteImport } from './routes/_authenticated/admin.recurso.$key'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoRoute = IntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => rootRouteImport,
} as any)
const GenteGestaoRoute = GenteGestaoRouteImport.update({
  id: '/gente-gestao',
  path: '/gente-gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulariosRoute = FormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturaRoute = CulturaRouteImport.update({
  id: '/cultura',
  path: '/cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicadosRoute = ComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenteGestaoIndexRoute = GenteGestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const ComunicadosIndexRoute = ComunicadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComunicadosRoute,
} as any)
const GenteGestaoPoliticasRoute = GenteGestaoPoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoHoleriteRoute = GenteGestaoHoleriteRouteImport.update({
  id: '/holerite',
  path: '/holerite',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoFeriasRoute = GenteGestaoFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoFaqRoute = GenteGestaoFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoDocumentosRoute = GenteGestaoDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoContatosRoute = GenteGestaoContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoCadastroRoute = GenteGestaoCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoBeneficiosRoute = GenteGestaoBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const GenteGestaoAtestadosRoute = GenteGestaoAtestadosRouteImport.update({
  id: '/atestados',
  path: '/atestados',
  getParentRoute: () => GenteGestaoRoute,
} as any)
const ComunicadosArquivoRoute = ComunicadosArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => ComunicadosRoute,
} as any)
const ComunicadosIdRoute = ComunicadosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ComunicadosRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicFilesSplatRoute = ApiPublicFilesSplatRouteImport.update({
  id: '/api/public/files/$',
  path: '/api/public/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRecursoKeyRoute =
  AuthenticatedAdminRecursoKeyRouteImport.update({
    id: '/recurso/$key',
    path: '/recurso/$key',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/comunicados': typeof ComunicadosRouteWithChildren
  '/cultura': typeof CulturaRoute
  '/formularios': typeof FormulariosRoute
  '/gate': typeof GateRoute
  '/gente-gestao': typeof GenteGestaoRouteWithChildren
  '/integracao': typeof IntegracaoRoute
  '/vagas': typeof VagasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/comunicados/$id': typeof ComunicadosIdRoute
  '/comunicados/arquivo': typeof ComunicadosArquivoRoute
  '/gente-gestao/atestados': typeof GenteGestaoAtestadosRoute
  '/gente-gestao/beneficios': typeof GenteGestaoBeneficiosRoute
  '/gente-gestao/cadastro': typeof GenteGestaoCadastroRoute
  '/gente-gestao/contatos': typeof GenteGestaoContatosRoute
  '/gente-gestao/documentos': typeof GenteGestaoDocumentosRoute
  '/gente-gestao/faq': typeof GenteGestaoFaqRoute
  '/gente-gestao/ferias': typeof GenteGestaoFeriasRoute
  '/gente-gestao/holerite': typeof GenteGestaoHoleriteRoute
  '/gente-gestao/politicas': typeof GenteGestaoPoliticasRoute
  '/comunicados/': typeof ComunicadosIndexRoute
  '/gente-gestao/': typeof GenteGestaoIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/recurso/$key': typeof AuthenticatedAdminRecursoKeyRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/cultura': typeof CulturaRoute
  '/formularios': typeof FormulariosRoute
  '/gate': typeof GateRoute
  '/integracao': typeof IntegracaoRoute
  '/vagas': typeof VagasRoute
  '/comunicados/$id': typeof ComunicadosIdRoute
  '/comunicados/arquivo': typeof ComunicadosArquivoRoute
  '/gente-gestao/atestados': typeof GenteGestaoAtestadosRoute
  '/gente-gestao/beneficios': typeof GenteGestaoBeneficiosRoute
  '/gente-gestao/cadastro': typeof GenteGestaoCadastroRoute
  '/gente-gestao/contatos': typeof GenteGestaoContatosRoute
  '/gente-gestao/documentos': typeof GenteGestaoDocumentosRoute
  '/gente-gestao/faq': typeof GenteGestaoFaqRoute
  '/gente-gestao/ferias': typeof GenteGestaoFeriasRoute
  '/gente-gestao/holerite': typeof GenteGestaoHoleriteRoute
  '/gente-gestao/politicas': typeof GenteGestaoPoliticasRoute
  '/comunicados': typeof ComunicadosIndexRoute
  '/gente-gestao': typeof GenteGestaoIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/recurso/$key': typeof AuthenticatedAdminRecursoKeyRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/comunicados': typeof ComunicadosRouteWithChildren
  '/cultura': typeof CulturaRoute
  '/formularios': typeof FormulariosRoute
  '/gate': typeof GateRoute
  '/gente-gestao': typeof GenteGestaoRouteWithChildren
  '/integracao': typeof IntegracaoRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/comunicados/$id': typeof ComunicadosIdRoute
  '/comunicados/arquivo': typeof ComunicadosArquivoRoute
  '/gente-gestao/atestados': typeof GenteGestaoAtestadosRoute
  '/gente-gestao/beneficios': typeof GenteGestaoBeneficiosRoute
  '/gente-gestao/cadastro': typeof GenteGestaoCadastroRoute
  '/gente-gestao/contatos': typeof GenteGestaoContatosRoute
  '/gente-gestao/documentos': typeof GenteGestaoDocumentosRoute
  '/gente-gestao/faq': typeof GenteGestaoFaqRoute
  '/gente-gestao/ferias': typeof GenteGestaoFeriasRoute
  '/gente-gestao/holerite': typeof GenteGestaoHoleriteRoute
  '/gente-gestao/politicas': typeof GenteGestaoPoliticasRoute
  '/comunicados/': typeof ComunicadosIndexRoute
  '/gente-gestao/': typeof GenteGestaoIndexRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/recurso/$key': typeof AuthenticatedAdminRecursoKeyRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/comunicados'
    | '/cultura'
    | '/formularios'
    | '/gate'
    | '/gente-gestao'
    | '/integracao'
    | '/vagas'
    | '/admin'
    | '/comunicados/$id'
    | '/comunicados/arquivo'
    | '/gente-gestao/atestados'
    | '/gente-gestao/beneficios'
    | '/gente-gestao/cadastro'
    | '/gente-gestao/contatos'
    | '/gente-gestao/documentos'
    | '/gente-gestao/faq'
    | '/gente-gestao/ferias'
    | '/gente-gestao/holerite'
    | '/gente-gestao/politicas'
    | '/comunicados/'
    | '/gente-gestao/'
    | '/admin/configuracoes'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/recurso/$key'
    | '/api/public/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/cultura'
    | '/formularios'
    | '/gate'
    | '/integracao'
    | '/vagas'
    | '/comunicados/$id'
    | '/comunicados/arquivo'
    | '/gente-gestao/atestados'
    | '/gente-gestao/beneficios'
    | '/gente-gestao/cadastro'
    | '/gente-gestao/contatos'
    | '/gente-gestao/documentos'
    | '/gente-gestao/faq'
    | '/gente-gestao/ferias'
    | '/gente-gestao/holerite'
    | '/gente-gestao/politicas'
    | '/comunicados'
    | '/gente-gestao'
    | '/admin/configuracoes'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/recurso/$key'
    | '/api/public/files/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/busca'
    | '/comunicados'
    | '/cultura'
    | '/formularios'
    | '/gate'
    | '/gente-gestao'
    | '/integracao'
    | '/vagas'
    | '/_authenticated/admin'
    | '/comunicados/$id'
    | '/comunicados/arquivo'
    | '/gente-gestao/atestados'
    | '/gente-gestao/beneficios'
    | '/gente-gestao/cadastro'
    | '/gente-gestao/contatos'
    | '/gente-gestao/documentos'
    | '/gente-gestao/faq'
    | '/gente-gestao/ferias'
    | '/gente-gestao/holerite'
    | '/gente-gestao/politicas'
    | '/comunicados/'
    | '/gente-gestao/'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/recurso/$key'
    | '/api/public/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  ComunicadosRoute: typeof ComunicadosRouteWithChildren
  CulturaRoute: typeof CulturaRoute
  FormulariosRoute: typeof FormulariosRoute
  GateRoute: typeof GateRoute
  GenteGestaoRoute: typeof GenteGestaoRouteWithChildren
  IntegracaoRoute: typeof IntegracaoRoute
  VagasRoute: typeof VagasRoute
  ApiPublicFilesSplatRoute: typeof ApiPublicFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao': {
      id: '/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof IntegracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gente-gestao': {
      id: '/gente-gestao'
      path: '/gente-gestao'
      fullPath: '/gente-gestao'
      preLoaderRoute: typeof GenteGestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formularios': {
      id: '/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof FormulariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultura': {
      id: '/cultura'
      path: '/cultura'
      fullPath: '/cultura'
      preLoaderRoute: typeof CulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicados': {
      id: '/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gente-gestao/': {
      id: '/gente-gestao/'
      path: '/'
      fullPath: '/gente-gestao/'
      preLoaderRoute: typeof GenteGestaoIndexRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/comunicados/': {
      id: '/comunicados/'
      path: '/'
      fullPath: '/comunicados/'
      preLoaderRoute: typeof ComunicadosIndexRouteImport
      parentRoute: typeof ComunicadosRoute
    }
    '/gente-gestao/politicas': {
      id: '/gente-gestao/politicas'
      path: '/politicas'
      fullPath: '/gente-gestao/politicas'
      preLoaderRoute: typeof GenteGestaoPoliticasRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/holerite': {
      id: '/gente-gestao/holerite'
      path: '/holerite'
      fullPath: '/gente-gestao/holerite'
      preLoaderRoute: typeof GenteGestaoHoleriteRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/ferias': {
      id: '/gente-gestao/ferias'
      path: '/ferias'
      fullPath: '/gente-gestao/ferias'
      preLoaderRoute: typeof GenteGestaoFeriasRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/faq': {
      id: '/gente-gestao/faq'
      path: '/faq'
      fullPath: '/gente-gestao/faq'
      preLoaderRoute: typeof GenteGestaoFaqRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/documentos': {
      id: '/gente-gestao/documentos'
      path: '/documentos'
      fullPath: '/gente-gestao/documentos'
      preLoaderRoute: typeof GenteGestaoDocumentosRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/contatos': {
      id: '/gente-gestao/contatos'
      path: '/contatos'
      fullPath: '/gente-gestao/contatos'
      preLoaderRoute: typeof GenteGestaoContatosRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/cadastro': {
      id: '/gente-gestao/cadastro'
      path: '/cadastro'
      fullPath: '/gente-gestao/cadastro'
      preLoaderRoute: typeof GenteGestaoCadastroRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/beneficios': {
      id: '/gente-gestao/beneficios'
      path: '/beneficios'
      fullPath: '/gente-gestao/beneficios'
      preLoaderRoute: typeof GenteGestaoBeneficiosRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/gente-gestao/atestados': {
      id: '/gente-gestao/atestados'
      path: '/atestados'
      fullPath: '/gente-gestao/atestados'
      preLoaderRoute: typeof GenteGestaoAtestadosRouteImport
      parentRoute: typeof GenteGestaoRoute
    }
    '/comunicados/arquivo': {
      id: '/comunicados/arquivo'
      path: '/arquivo'
      fullPath: '/comunicados/arquivo'
      preLoaderRoute: typeof ComunicadosArquivoRouteImport
      parentRoute: typeof ComunicadosRoute
    }
    '/comunicados/$id': {
      id: '/comunicados/$id'
      path: '/$id'
      fullPath: '/comunicados/$id'
      preLoaderRoute: typeof ComunicadosIdRouteImport
      parentRoute: typeof ComunicadosRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/files/$': {
      id: '/api/public/files/$'
      path: '/api/public/files/$'
      fullPath: '/api/public/files/$'
      preLoaderRoute: typeof ApiPublicFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/recurso/$key': {
      id: '/_authenticated/admin/recurso/$key'
      path: '/recurso/$key'
      fullPath: '/admin/recurso/$key'
      preLoaderRoute: typeof AuthenticatedAdminRecursoKeyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRecursoKeyRoute: typeof AuthenticatedAdminRecursoKeyRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminRecursoKeyRoute: AuthenticatedAdminRecursoKeyRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ComunicadosRouteChildren {
  ComunicadosIdRoute: typeof ComunicadosIdRoute
  ComunicadosArquivoRoute: typeof ComunicadosArquivoRoute
  ComunicadosIndexRoute: typeof ComunicadosIndexRoute
}

const ComunicadosRouteChildren: ComunicadosRouteChildren = {
  ComunicadosIdRoute: ComunicadosIdRoute,
  ComunicadosArquivoRoute: ComunicadosArquivoRoute,
  ComunicadosIndexRoute: ComunicadosIndexRoute,
}

const ComunicadosRouteWithChildren = ComunicadosRoute._addFileChildren(
  ComunicadosRouteChildren,
)

interface GenteGestaoRouteChildren {
  GenteGestaoAtestadosRoute: typeof GenteGestaoAtestadosRoute
  GenteGestaoBeneficiosRoute: typeof GenteGestaoBeneficiosRoute
  GenteGestaoCadastroRoute: typeof GenteGestaoCadastroRoute
  GenteGestaoContatosRoute: typeof GenteGestaoContatosRoute
  GenteGestaoDocumentosRoute: typeof GenteGestaoDocumentosRoute
  GenteGestaoFaqRoute: typeof GenteGestaoFaqRoute
  GenteGestaoFeriasRoute: typeof GenteGestaoFeriasRoute
  GenteGestaoHoleriteRoute: typeof GenteGestaoHoleriteRoute
  GenteGestaoPoliticasRoute: typeof GenteGestaoPoliticasRoute
  GenteGestaoIndexRoute: typeof GenteGestaoIndexRoute
}

const GenteGestaoRouteChildren: GenteGestaoRouteChildren = {
  GenteGestaoAtestadosRoute: GenteGestaoAtestadosRoute,
  GenteGestaoBeneficiosRoute: GenteGestaoBeneficiosRoute,
  GenteGestaoCadastroRoute: GenteGestaoCadastroRoute,
  GenteGestaoContatosRoute: GenteGestaoContatosRoute,
  GenteGestaoDocumentosRoute: GenteGestaoDocumentosRoute,
  GenteGestaoFaqRoute: GenteGestaoFaqRoute,
  GenteGestaoFeriasRoute: GenteGestaoFeriasRoute,
  GenteGestaoHoleriteRoute: GenteGestaoHoleriteRoute,
  GenteGestaoPoliticasRoute: GenteGestaoPoliticasRoute,
  GenteGestaoIndexRoute: GenteGestaoIndexRoute,
}

const GenteGestaoRouteWithChildren = GenteGestaoRoute._addFileChildren(
  GenteGestaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  ComunicadosRoute: ComunicadosRouteWithChildren,
  CulturaRoute: CulturaRoute,
  FormulariosRoute: FormulariosRoute,
  GateRoute: GateRoute,
  GenteGestaoRoute: GenteGestaoRouteWithChildren,
  IntegracaoRoute: IntegracaoRoute,
  VagasRoute: VagasRoute,
  ApiPublicFilesSplatRoute: ApiPublicFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
