/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GateRouteImport } from './routes/gate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PortalIndexRouteImport } from './routes/_portal.index'
import { Route as ColaboradorRecuperarSenhaRouteImport } from './routes/colaborador/recuperar-senha'
import { Route as ColaboradorConfirmarRouteImport } from './routes/colaborador/confirmar'
import { Route as PortalVagasRouteImport } from './routes/_portal.vagas'
import { Route as PortalPerfilRouteImport } from './routes/_portal.perfil'
import { Route as PortalMuralRouteImport } from './routes/_portal.mural'
import { Route as PortalIntegracaoRouteImport } from './routes/_portal.integracao'
import { Route as PortalGenteGestaoRouteImport } from './routes/_portal.gente-gestao'
import { Route as PortalFormulariosRouteImport } from './routes/_portal.formularios'
import { Route as PortalCulturaRouteImport } from './routes/_portal.cultura'
import { Route as PortalComunicadosRouteImport } from './routes/_portal.comunicados'
import { Route as PortalBuscaRouteImport } from './routes/_portal.busca'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PortalMuralIndexRouteImport } from './routes/_portal.mural.index'
import { Route as PortalGenteGestaoIndexRouteImport } from './routes/_portal.gente-gestao.index'
import { Route as PortalComunicadosIndexRouteImport } from './routes/_portal.comunicados.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as PortalMuralArquivoRouteImport } from './routes/_portal.mural.arquivo'
import { Route as PortalMuralIdRouteImport } from './routes/_portal.mural.$id'
import { Route as PortalGenteGestaoPoliticasRouteImport } from './routes/_portal.gente-gestao.politicas'
import { Route as PortalGenteGestaoHoleriteRouteImport } from './routes/_portal.gente-gestao.holerite'
import { Route as PortalGenteGestaoFeriasRouteImport } from './routes/_portal.gente-gestao.ferias'
import { Route as PortalGenteGestaoFaqRouteImport } from './routes/_portal.gente-gestao.faq'
import { Route as PortalGenteGestaoDocumentosRouteImport } from './routes/_portal.gente-gestao.documentos'
import { Route as PortalGenteGestaoContatosRouteImport } from './routes/_portal.gente-gestao.contatos'
import { Route as PortalGenteGestaoCadastroRouteImport } from './routes/_portal.gente-gestao.cadastro'
import { Route as PortalGenteGestaoBeneficiosRouteImport } from './routes/_portal.gente-gestao.beneficios'
import { Route as PortalGenteGestaoAtestadosRouteImport } from './routes/_portal.gente-gestao.atestados'
import { Route as PortalComunicadosArquivoRouteImport } from './routes/_portal.comunicados.arquivo'
import { Route as PortalComunicadosIdRouteImport } from './routes/_portal.comunicados.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSolicitacoesRouteImport } from './routes/_authenticated/admin.solicitacoes'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminColaboradoresRouteImport } from './routes/_authenticated/admin.colaboradores'
import { Route as ApiPublicFilesSplatRouteImport } from './routes/api/public/files/$'
import { Route as AuthenticatedAdminRecursoKeyRouteImport } from './routes/_authenticated/admin.recurso.$key'

const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ColaboradorRecuperarSenhaRoute =
  ColaboradorRecuperarSenhaRouteImport.update({
    id: '/colaborador/recuperar-senha',
    path: '/colaborador/recuperar-senha',
    getParentRoute: () => rootRouteImport,
  } as any)
const ColaboradorConfirmarRoute = ColaboradorConfirmarRouteImport.update({
  id: '/colaborador/confirmar',
  path: '/colaborador/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalVagasRoute = PortalVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMuralRoute = PortalMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => PortalRoute,
} as any)
const PortalIntegracaoRoute = PortalIntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGenteGestaoRoute = PortalGenteGestaoRouteImport.update({
  id: '/gente-gestao',
  path: '/gente-gestao',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFormulariosRoute = PortalFormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCulturaRoute = PortalCulturaRouteImport.update({
  id: '/cultura',
  path: '/cultura',
  getParentRoute: () => PortalRoute,
} as any)
const PortalComunicadosRoute = PortalComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBuscaRoute = PortalBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalMuralIndexRoute = PortalMuralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalMuralRoute,
} as any)
const PortalGenteGestaoIndexRoute = PortalGenteGestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalGenteGestaoRoute,
} as any)
const PortalComunicadosIndexRoute = PortalComunicadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalComunicadosRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PortalMuralArquivoRoute = PortalMuralArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => PortalMuralRoute,
} as any)
const PortalMuralIdRoute = PortalMuralIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalMuralRoute,
} as any)
const PortalGenteGestaoPoliticasRoute =
  PortalGenteGestaoPoliticasRouteImport.update({
    id: '/politicas',
    path: '/politicas',
    getParentRoute: () => PortalGenteGestaoRoute,
  } as any)
const PortalGenteGestaoHoleriteRoute =
  PortalGenteGestaoHoleriteRouteImport.update({
    id: '/holerite',
    path: '/holerite',
    getParentRoute: () => PortalGenteGestaoRoute,
  } as any)
const PortalGenteGestaoFeriasRoute = PortalGenteGestaoFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => PortalGenteGestaoRoute,
} as any)
const PortalGenteGestaoFaqRoute = PortalGenteGestaoFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PortalGenteGestaoRoute,
} as any)
const PortalGenteGestaoDocumentosRoute =
  PortalGenteGestaoDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => PortalGenteGestaoRoute,
  } as any)
const PortalGenteGestaoContatosRoute =
  PortalGenteGestaoContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => PortalGenteGestaoRoute,
  } as any)
const PortalGenteGestaoCadastroRoute =
  PortalGenteGestaoCadastroRouteImport.update({
    id: '/cadastro',
    path: '/cadastro',
    getParentRoute: () => PortalGenteGestaoRoute,
  } as any)
const PortalGenteGestaoBeneficiosRoute =
  PortalGenteGestaoBeneficiosRouteImport.update({
    id: '/beneficios',
    path: '/beneficios',
    getParentRoute: () => PortalGenteGestaoRoute,
  } as any)
const PortalGenteGestaoAtestadosRoute =
  PortalGenteGestaoAtestadosRouteImport.update({
    id: '/atestados',
    path: '/atestados',
    getParentRoute: () => PortalGenteGestaoRoute,
  } as any)
const PortalComunicadosArquivoRoute =
  PortalComunicadosArquivoRouteImport.update({
    id: '/arquivo',
    path: '/arquivo',
    getParentRoute: () => PortalComunicadosRoute,
  } as any)
const PortalComunicadosIdRoute = PortalComunicadosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalComunicadosRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSolicitacoesRoute =
  AuthenticatedAdminSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminColaboradoresRoute =
  AuthenticatedAdminColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicFilesSplatRoute = ApiPublicFilesSplatRouteImport.update({
  id: '/api/public/files/$',
  path: '/api/public/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRecursoKeyRoute =
  AuthenticatedAdminRecursoKeyRouteImport.update({
    id: '/recurso/$key',
    path: '/recurso/$key',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/auth': typeof AuthRoute
  '/gate': typeof GateRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/busca': typeof PortalBuscaRoute
  '/comunicados': typeof PortalComunicadosRouteWithChildren
  '/cultura': typeof PortalCulturaRoute
  '/formularios': typeof PortalFormulariosRoute
  '/gente-gestao': typeof PortalGenteGestaoRouteWithChildren
  '/integracao': typeof PortalIntegracaoRoute
  '/mural': typeof PortalMuralRouteWithChildren
  '/perfil': typeof PortalPerfilRoute
  '/vagas': typeof PortalVagasRoute
  '/colaborador/confirmar': typeof ColaboradorConfirmarRoute
  '/colaborador/recuperar-senha': typeof ColaboradorRecuperarSenhaRoute
  '/admin/colaboradores': typeof AuthenticatedAdminColaboradoresRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/comunicados/$id': typeof PortalComunicadosIdRoute
  '/comunicados/arquivo': typeof PortalComunicadosArquivoRoute
  '/gente-gestao/atestados': typeof PortalGenteGestaoAtestadosRoute
  '/gente-gestao/beneficios': typeof PortalGenteGestaoBeneficiosRoute
  '/gente-gestao/cadastro': typeof PortalGenteGestaoCadastroRoute
  '/gente-gestao/contatos': typeof PortalGenteGestaoContatosRoute
  '/gente-gestao/documentos': typeof PortalGenteGestaoDocumentosRoute
  '/gente-gestao/faq': typeof PortalGenteGestaoFaqRoute
  '/gente-gestao/ferias': typeof PortalGenteGestaoFeriasRoute
  '/gente-gestao/holerite': typeof PortalGenteGestaoHoleriteRoute
  '/gente-gestao/politicas': typeof PortalGenteGestaoPoliticasRoute
  '/mural/$id': typeof PortalMuralIdRoute
  '/mural/arquivo': typeof PortalMuralArquivoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/comunicados/': typeof PortalComunicadosIndexRoute
  '/gente-gestao/': typeof PortalGenteGestaoIndexRoute
  '/mural/': typeof PortalMuralIndexRoute
  '/admin/recurso/$key': typeof AuthenticatedAdminRecursoKeyRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PortalIndexRoute
  '/auth': typeof AuthRoute
  '/gate': typeof GateRoute
  '/busca': typeof PortalBuscaRoute
  '/cultura': typeof PortalCulturaRoute
  '/formularios': typeof PortalFormulariosRoute
  '/integracao': typeof PortalIntegracaoRoute
  '/perfil': typeof PortalPerfilRoute
  '/vagas': typeof PortalVagasRoute
  '/colaborador/confirmar': typeof ColaboradorConfirmarRoute
  '/colaborador/recuperar-senha': typeof ColaboradorRecuperarSenhaRoute
  '/admin/colaboradores': typeof AuthenticatedAdminColaboradoresRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/comunicados/$id': typeof PortalComunicadosIdRoute
  '/comunicados/arquivo': typeof PortalComunicadosArquivoRoute
  '/gente-gestao/atestados': typeof PortalGenteGestaoAtestadosRoute
  '/gente-gestao/beneficios': typeof PortalGenteGestaoBeneficiosRoute
  '/gente-gestao/cadastro': typeof PortalGenteGestaoCadastroRoute
  '/gente-gestao/contatos': typeof PortalGenteGestaoContatosRoute
  '/gente-gestao/documentos': typeof PortalGenteGestaoDocumentosRoute
  '/gente-gestao/faq': typeof PortalGenteGestaoFaqRoute
  '/gente-gestao/ferias': typeof PortalGenteGestaoFeriasRoute
  '/gente-gestao/holerite': typeof PortalGenteGestaoHoleriteRoute
  '/gente-gestao/politicas': typeof PortalGenteGestaoPoliticasRoute
  '/mural/$id': typeof PortalMuralIdRoute
  '/mural/arquivo': typeof PortalMuralArquivoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/comunicados': typeof PortalComunicadosIndexRoute
  '/gente-gestao': typeof PortalGenteGestaoIndexRoute
  '/mural': typeof PortalMuralIndexRoute
  '/admin/recurso/$key': typeof AuthenticatedAdminRecursoKeyRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/auth': typeof AuthRoute
  '/gate': typeof GateRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_portal/busca': typeof PortalBuscaRoute
  '/_portal/comunicados': typeof PortalComunicadosRouteWithChildren
  '/_portal/cultura': typeof PortalCulturaRoute
  '/_portal/formularios': typeof PortalFormulariosRoute
  '/_portal/gente-gestao': typeof PortalGenteGestaoRouteWithChildren
  '/_portal/integracao': typeof PortalIntegracaoRoute
  '/_portal/mural': typeof PortalMuralRouteWithChildren
  '/_portal/perfil': typeof PortalPerfilRoute
  '/_portal/vagas': typeof PortalVagasRoute
  '/colaborador/confirmar': typeof ColaboradorConfirmarRoute
  '/colaborador/recuperar-senha': typeof ColaboradorRecuperarSenhaRoute
  '/_portal/': typeof PortalIndexRoute
  '/_authenticated/admin/colaboradores': typeof AuthenticatedAdminColaboradoresRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_portal/comunicados/$id': typeof PortalComunicadosIdRoute
  '/_portal/comunicados/arquivo': typeof PortalComunicadosArquivoRoute
  '/_portal/gente-gestao/atestados': typeof PortalGenteGestaoAtestadosRoute
  '/_portal/gente-gestao/beneficios': typeof PortalGenteGestaoBeneficiosRoute
  '/_portal/gente-gestao/cadastro': typeof PortalGenteGestaoCadastroRoute
  '/_portal/gente-gestao/contatos': typeof PortalGenteGestaoContatosRoute
  '/_portal/gente-gestao/documentos': typeof PortalGenteGestaoDocumentosRoute
  '/_portal/gente-gestao/faq': typeof PortalGenteGestaoFaqRoute
  '/_portal/gente-gestao/ferias': typeof PortalGenteGestaoFeriasRoute
  '/_portal/gente-gestao/holerite': typeof PortalGenteGestaoHoleriteRoute
  '/_portal/gente-gestao/politicas': typeof PortalGenteGestaoPoliticasRoute
  '/_portal/mural/$id': typeof PortalMuralIdRoute
  '/_portal/mural/arquivo': typeof PortalMuralArquivoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_portal/comunicados/': typeof PortalComunicadosIndexRoute
  '/_portal/gente-gestao/': typeof PortalGenteGestaoIndexRoute
  '/_portal/mural/': typeof PortalMuralIndexRoute
  '/_authenticated/admin/recurso/$key': typeof AuthenticatedAdminRecursoKeyRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gate'
    | '/admin'
    | '/busca'
    | '/comunicados'
    | '/cultura'
    | '/formularios'
    | '/gente-gestao'
    | '/integracao'
    | '/mural'
    | '/perfil'
    | '/vagas'
    | '/colaborador/confirmar'
    | '/colaborador/recuperar-senha'
    | '/admin/colaboradores'
    | '/admin/configuracoes'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/comunicados/$id'
    | '/comunicados/arquivo'
    | '/gente-gestao/atestados'
    | '/gente-gestao/beneficios'
    | '/gente-gestao/cadastro'
    | '/gente-gestao/contatos'
    | '/gente-gestao/documentos'
    | '/gente-gestao/faq'
    | '/gente-gestao/ferias'
    | '/gente-gestao/holerite'
    | '/gente-gestao/politicas'
    | '/mural/$id'
    | '/mural/arquivo'
    | '/admin/'
    | '/comunicados/'
    | '/gente-gestao/'
    | '/mural/'
    | '/admin/recurso/$key'
    | '/api/public/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gate'
    | '/busca'
    | '/cultura'
    | '/formularios'
    | '/integracao'
    | '/perfil'
    | '/vagas'
    | '/colaborador/confirmar'
    | '/colaborador/recuperar-senha'
    | '/admin/colaboradores'
    | '/admin/configuracoes'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/comunicados/$id'
    | '/comunicados/arquivo'
    | '/gente-gestao/atestados'
    | '/gente-gestao/beneficios'
    | '/gente-gestao/cadastro'
    | '/gente-gestao/contatos'
    | '/gente-gestao/documentos'
    | '/gente-gestao/faq'
    | '/gente-gestao/ferias'
    | '/gente-gestao/holerite'
    | '/gente-gestao/politicas'
    | '/mural/$id'
    | '/mural/arquivo'
    | '/admin'
    | '/comunicados'
    | '/gente-gestao'
    | '/mural'
    | '/admin/recurso/$key'
    | '/api/public/files/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_portal'
    | '/auth'
    | '/gate'
    | '/_authenticated/admin'
    | '/_portal/busca'
    | '/_portal/comunicados'
    | '/_portal/cultura'
    | '/_portal/formularios'
    | '/_portal/gente-gestao'
    | '/_portal/integracao'
    | '/_portal/mural'
    | '/_portal/perfil'
    | '/_portal/vagas'
    | '/colaborador/confirmar'
    | '/colaborador/recuperar-senha'
    | '/_portal/'
    | '/_authenticated/admin/colaboradores'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/solicitacoes'
    | '/_authenticated/admin/usuarios'
    | '/_portal/comunicados/$id'
    | '/_portal/comunicados/arquivo'
    | '/_portal/gente-gestao/atestados'
    | '/_portal/gente-gestao/beneficios'
    | '/_portal/gente-gestao/cadastro'
    | '/_portal/gente-gestao/contatos'
    | '/_portal/gente-gestao/documentos'
    | '/_portal/gente-gestao/faq'
    | '/_portal/gente-gestao/ferias'
    | '/_portal/gente-gestao/holerite'
    | '/_portal/gente-gestao/politicas'
    | '/_portal/mural/$id'
    | '/_portal/mural/arquivo'
    | '/_authenticated/admin/'
    | '/_portal/comunicados/'
    | '/_portal/gente-gestao/'
    | '/_portal/mural/'
    | '/_authenticated/admin/recurso/$key'
    | '/api/public/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  AuthRoute: typeof AuthRoute
  GateRoute: typeof GateRoute
  ColaboradorConfirmarRoute: typeof ColaboradorConfirmarRoute
  ColaboradorRecuperarSenhaRoute: typeof ColaboradorRecuperarSenhaRoute
  ApiPublicFilesSplatRoute: typeof ApiPublicFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/colaborador/recuperar-senha': {
      id: '/colaborador/recuperar-senha'
      path: '/colaborador/recuperar-senha'
      fullPath: '/colaborador/recuperar-senha'
      preLoaderRoute: typeof ColaboradorRecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/confirmar': {
      id: '/colaborador/confirmar'
      path: '/colaborador/confirmar'
      fullPath: '/colaborador/confirmar'
      preLoaderRoute: typeof ColaboradorConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/vagas': {
      id: '/_portal/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof PortalVagasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/perfil': {
      id: '/_portal/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/mural': {
      id: '/_portal/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof PortalMuralRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/integracao': {
      id: '/_portal/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof PortalIntegracaoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/gente-gestao': {
      id: '/_portal/gente-gestao'
      path: '/gente-gestao'
      fullPath: '/gente-gestao'
      preLoaderRoute: typeof PortalGenteGestaoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/formularios': {
      id: '/_portal/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof PortalFormulariosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/cultura': {
      id: '/_portal/cultura'
      path: '/cultura'
      fullPath: '/cultura'
      preLoaderRoute: typeof PortalCulturaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/comunicados': {
      id: '/_portal/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof PortalComunicadosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/busca': {
      id: '/_portal/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof PortalBuscaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_portal/mural/': {
      id: '/_portal/mural/'
      path: '/'
      fullPath: '/mural/'
      preLoaderRoute: typeof PortalMuralIndexRouteImport
      parentRoute: typeof PortalMuralRoute
    }
    '/_portal/gente-gestao/': {
      id: '/_portal/gente-gestao/'
      path: '/'
      fullPath: '/gente-gestao/'
      preLoaderRoute: typeof PortalGenteGestaoIndexRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/comunicados/': {
      id: '/_portal/comunicados/'
      path: '/'
      fullPath: '/comunicados/'
      preLoaderRoute: typeof PortalComunicadosIndexRouteImport
      parentRoute: typeof PortalComunicadosRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_portal/mural/arquivo': {
      id: '/_portal/mural/arquivo'
      path: '/arquivo'
      fullPath: '/mural/arquivo'
      preLoaderRoute: typeof PortalMuralArquivoRouteImport
      parentRoute: typeof PortalMuralRoute
    }
    '/_portal/mural/$id': {
      id: '/_portal/mural/$id'
      path: '/$id'
      fullPath: '/mural/$id'
      preLoaderRoute: typeof PortalMuralIdRouteImport
      parentRoute: typeof PortalMuralRoute
    }
    '/_portal/gente-gestao/politicas': {
      id: '/_portal/gente-gestao/politicas'
      path: '/politicas'
      fullPath: '/gente-gestao/politicas'
      preLoaderRoute: typeof PortalGenteGestaoPoliticasRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/holerite': {
      id: '/_portal/gente-gestao/holerite'
      path: '/holerite'
      fullPath: '/gente-gestao/holerite'
      preLoaderRoute: typeof PortalGenteGestaoHoleriteRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/ferias': {
      id: '/_portal/gente-gestao/ferias'
      path: '/ferias'
      fullPath: '/gente-gestao/ferias'
      preLoaderRoute: typeof PortalGenteGestaoFeriasRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/faq': {
      id: '/_portal/gente-gestao/faq'
      path: '/faq'
      fullPath: '/gente-gestao/faq'
      preLoaderRoute: typeof PortalGenteGestaoFaqRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/documentos': {
      id: '/_portal/gente-gestao/documentos'
      path: '/documentos'
      fullPath: '/gente-gestao/documentos'
      preLoaderRoute: typeof PortalGenteGestaoDocumentosRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/contatos': {
      id: '/_portal/gente-gestao/contatos'
      path: '/contatos'
      fullPath: '/gente-gestao/contatos'
      preLoaderRoute: typeof PortalGenteGestaoContatosRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/cadastro': {
      id: '/_portal/gente-gestao/cadastro'
      path: '/cadastro'
      fullPath: '/gente-gestao/cadastro'
      preLoaderRoute: typeof PortalGenteGestaoCadastroRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/beneficios': {
      id: '/_portal/gente-gestao/beneficios'
      path: '/beneficios'
      fullPath: '/gente-gestao/beneficios'
      preLoaderRoute: typeof PortalGenteGestaoBeneficiosRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/gente-gestao/atestados': {
      id: '/_portal/gente-gestao/atestados'
      path: '/atestados'
      fullPath: '/gente-gestao/atestados'
      preLoaderRoute: typeof PortalGenteGestaoAtestadosRouteImport
      parentRoute: typeof PortalGenteGestaoRoute
    }
    '/_portal/comunicados/arquivo': {
      id: '/_portal/comunicados/arquivo'
      path: '/arquivo'
      fullPath: '/comunicados/arquivo'
      preLoaderRoute: typeof PortalComunicadosArquivoRouteImport
      parentRoute: typeof PortalComunicadosRoute
    }
    '/_portal/comunicados/$id': {
      id: '/_portal/comunicados/$id'
      path: '/$id'
      fullPath: '/comunicados/$id'
      preLoaderRoute: typeof PortalComunicadosIdRouteImport
      parentRoute: typeof PortalComunicadosRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/solicitacoes': {
      id: '/_authenticated/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/colaboradores': {
      id: '/_authenticated/admin/colaboradores'
      path: '/colaboradores'
      fullPath: '/admin/colaboradores'
      preLoaderRoute: typeof AuthenticatedAdminColaboradoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/files/$': {
      id: '/api/public/files/$'
      path: '/api/public/files/$'
      fullPath: '/api/public/files/$'
      preLoaderRoute: typeof ApiPublicFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/recurso/$key': {
      id: '/_authenticated/admin/recurso/$key'
      path: '/recurso/$key'
      fullPath: '/admin/recurso/$key'
      preLoaderRoute: typeof AuthenticatedAdminRecursoKeyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminColaboradoresRoute: typeof AuthenticatedAdminColaboradoresRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminSolicitacoesRoute: typeof AuthenticatedAdminSolicitacoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRecursoKeyRoute: typeof AuthenticatedAdminRecursoKeyRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminColaboradoresRoute: AuthenticatedAdminColaboradoresRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminSolicitacoesRoute: AuthenticatedAdminSolicitacoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminRecursoKeyRoute: AuthenticatedAdminRecursoKeyRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalComunicadosRouteChildren {
  PortalComunicadosIdRoute: typeof PortalComunicadosIdRoute
  PortalComunicadosArquivoRoute: typeof PortalComunicadosArquivoRoute
  PortalComunicadosIndexRoute: typeof PortalComunicadosIndexRoute
}

const PortalComunicadosRouteChildren: PortalComunicadosRouteChildren = {
  PortalComunicadosIdRoute: PortalComunicadosIdRoute,
  PortalComunicadosArquivoRoute: PortalComunicadosArquivoRoute,
  PortalComunicadosIndexRoute: PortalComunicadosIndexRoute,
}

const PortalComunicadosRouteWithChildren =
  PortalComunicadosRoute._addFileChildren(PortalComunicadosRouteChildren)

interface PortalGenteGestaoRouteChildren {
  PortalGenteGestaoAtestadosRoute: typeof PortalGenteGestaoAtestadosRoute
  PortalGenteGestaoBeneficiosRoute: typeof PortalGenteGestaoBeneficiosRoute
  PortalGenteGestaoCadastroRoute: typeof PortalGenteGestaoCadastroRoute
  PortalGenteGestaoContatosRoute: typeof PortalGenteGestaoContatosRoute
  PortalGenteGestaoDocumentosRoute: typeof PortalGenteGestaoDocumentosRoute
  PortalGenteGestaoFaqRoute: typeof PortalGenteGestaoFaqRoute
  PortalGenteGestaoFeriasRoute: typeof PortalGenteGestaoFeriasRoute
  PortalGenteGestaoHoleriteRoute: typeof PortalGenteGestaoHoleriteRoute
  PortalGenteGestaoPoliticasRoute: typeof PortalGenteGestaoPoliticasRoute
  PortalGenteGestaoIndexRoute: typeof PortalGenteGestaoIndexRoute
}

const PortalGenteGestaoRouteChildren: PortalGenteGestaoRouteChildren = {
  PortalGenteGestaoAtestadosRoute: PortalGenteGestaoAtestadosRoute,
  PortalGenteGestaoBeneficiosRoute: PortalGenteGestaoBeneficiosRoute,
  PortalGenteGestaoCadastroRoute: PortalGenteGestaoCadastroRoute,
  PortalGenteGestaoContatosRoute: PortalGenteGestaoContatosRoute,
  PortalGenteGestaoDocumentosRoute: PortalGenteGestaoDocumentosRoute,
  PortalGenteGestaoFaqRoute: PortalGenteGestaoFaqRoute,
  PortalGenteGestaoFeriasRoute: PortalGenteGestaoFeriasRoute,
  PortalGenteGestaoHoleriteRoute: PortalGenteGestaoHoleriteRoute,
  PortalGenteGestaoPoliticasRoute: PortalGenteGestaoPoliticasRoute,
  PortalGenteGestaoIndexRoute: PortalGenteGestaoIndexRoute,
}

const PortalGenteGestaoRouteWithChildren =
  PortalGenteGestaoRoute._addFileChildren(PortalGenteGestaoRouteChildren)

interface PortalMuralRouteChildren {
  PortalMuralIdRoute: typeof PortalMuralIdRoute
  PortalMuralArquivoRoute: typeof PortalMuralArquivoRoute
  PortalMuralIndexRoute: typeof PortalMuralIndexRoute
}

const PortalMuralRouteChildren: PortalMuralRouteChildren = {
  PortalMuralIdRoute: PortalMuralIdRoute,
  PortalMuralArquivoRoute: PortalMuralArquivoRoute,
  PortalMuralIndexRoute: PortalMuralIndexRoute,
}

const PortalMuralRouteWithChildren = PortalMuralRoute._addFileChildren(
  PortalMuralRouteChildren,
)

interface PortalRouteChildren {
  PortalBuscaRoute: typeof PortalBuscaRoute
  PortalComunicadosRoute: typeof PortalComunicadosRouteWithChildren
  PortalCulturaRoute: typeof PortalCulturaRoute
  PortalFormulariosRoute: typeof PortalFormulariosRoute
  PortalGenteGestaoRoute: typeof PortalGenteGestaoRouteWithChildren
  PortalIntegracaoRoute: typeof PortalIntegracaoRoute
  PortalMuralRoute: typeof PortalMuralRouteWithChildren
  PortalPerfilRoute: typeof PortalPerfilRoute
  PortalVagasRoute: typeof PortalVagasRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBuscaRoute: PortalBuscaRoute,
  PortalComunicadosRoute: PortalComunicadosRouteWithChildren,
  PortalCulturaRoute: PortalCulturaRoute,
  PortalFormulariosRoute: PortalFormulariosRoute,
  PortalGenteGestaoRoute: PortalGenteGestaoRouteWithChildren,
  PortalIntegracaoRoute: PortalIntegracaoRoute,
  PortalMuralRoute: PortalMuralRouteWithChildren,
  PortalPerfilRoute: PortalPerfilRoute,
  PortalVagasRoute: PortalVagasRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  AuthRoute: AuthRoute,
  GateRoute: GateRoute,
  ColaboradorConfirmarRoute: ColaboradorConfirmarRoute,
  ColaboradorRecuperarSenhaRoute: ColaboradorRecuperarSenhaRoute,
  ApiPublicFilesSplatRoute: ApiPublicFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
